# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d3d364ed6c234504cf86910dfa86f95feabdb81a2c5f028c0eaa2cbde7a8692204aa26f57860d78da72e7596a01aedd66bdbde7fa0b4fe227069a36a94ebba

test:
  secret_key_base: 5be6922fe27b6a93018c0da1f2db8238103054a143f3d132a7833dce45a58ef0c312740850519351f6ac70b959268ff98eced32bec5faa7b0fc801242c725a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
